{
 "title": "HarperDB Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobs", "label": "Job(s)", "query": { "query": "label_values(job)" } },
   {
    "name": "instances",
    "label": "Instance(s)",
    "query": {
     "query": "label_values({job=~\"$jobs\"},instance)"
    }
   },
   {
    "name": "quantiles",
    "label": "Quantile(s)",
    "query": {
     "query": "label_values({job=~\"$jobs\"},quantile)"
    }
   },
   {
    "name": "paths",
    "label": "Path(s)",
    "query": {
     "query": "label_values({job=~\"$jobs\"},path)"
    }
   },
   {
    "name": "methods",
    "label": "Method(s)",
    "query": {
     "query": "label_values({job=~\"$jobs\"},method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HarperDB Duration",
   "type": "timeseries",
   "description": "Duration of all HarperDB executions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "duration{job=~\"$jobs\", instance=~\"$instances\", quantile=~\"$quantiles\", path=~\"$paths\", method=~\"$methods\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HarperDB Duration by Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by(quantile) (duration{job=~\"$jobs\", instance=~\"$instances\", quantile=~\"$quantiles\", path=~\"$paths\", method=~\"$methods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HarperDB Duration per Node per Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(instance, path) (duration{job=~\"$jobs\", instance=~\"$instances\", quantile=~\"$quantiles\", path=~\"$paths\", method=~\"$methods\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Count (Hits) per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "duration_count{job=~\"$jobs\", instance=~\"$instances\", path=~\"$paths\", method=~\"$methods\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HarperDB Process CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "harperdb_process_cpu_utilization{job=~\"$jobs\", instance=~\"$instances\"}",
     "legendFormat": "{{instance}} {{process_name}}"
    }
   ]
  },
  {
   "title": "Duration Count per Method/Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(path, method) (duration_count{job=~\"$jobs\", instance=~\"$instances\", path=~\"$paths\", method=~\"$methods\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}